export const locales = {
  en: {
    meta: {
      title: 'EMCL Heavy Equipment Reservation System',
      subject: 'Customer Presentation',
      outfile: 'EMCL-Heavy-Equipment-Reservation-System.pptx',
    },
    footer: 'ExxonMobil Cepu Limited — Internal Use',
    s1: {
      title: 'EMCL Heavy Equipment\nReservation System',
      subtitle: 'Digital platform for cranes, forklifts, manlifts & lifting operations',
      date: 'ExxonMobil Cepu Limited  |  Customer Presentation  |  June 2026',
    },
    s2: {
      h: 'Executive Summary',
      sub: 'Replacing legacy lifting plan software with a modern web platform',
      metrics: ['Database Tables', 'User Roles', 'Equipment Types', 'Audit Trail'],
      bullets: [
        'Centralized equipment booking across EMCL Cepu sites',
        'Automated conflict detection prevents double-booking',
        'Structured approval workflow with full compliance logging',
        'Phase 1 delivered — ready for pilot deployment on Vercel + Neon PostgreSQL',
      ],
    },
    s3: {
      h: 'Business Challenge',
      sub: 'Why a new system is needed',
      rows: [
        ['Manual / legacy lifting plans', 'Delays, errors, poor visibility'],
        ['Double-booking of equipment', 'Schedule conflicts & downtime'],
        ['Unclear approval process', 'Slow decisions, compliance risk'],
        ['Limited cross-site visibility', 'Hard to plan equipment usage'],
        ['Paper / email tracking', 'Weak audit trail for audits'],
      ],
    },
    s4: {
      h: 'Solution Overview',
      sub: 'End-to-end equipment reservation lifecycle',
      steps: [
        ['1. Request', 'Select equipment\n& date range'],
        ['2. Detect', 'Conflict check\n& alternatives'],
        ['3. Approve', 'Approver review\n& decision'],
        ['4. Track', 'Calendar, status\n& notifications'],
      ],
      banner: 'Single web portal accessible from desktop & mobile (PWA-ready)  •  Role-based access  •  ExxonMobil Cepu branded UI',
    },
    s5: {
      h: 'User Roles & Access Control',
      sub: 'Three roles — one login portal',
      roles: [
        { t: 'REQUESTOR', items: 'Submit requests\nView My Requests\nEquipment calendar' },
        { t: 'APPROVER', items: 'All Requestor features\nApprovals queue\nApprove / Reject + notes' },
        { t: 'ADMIN', items: 'All Approver features\nEquipment CRUD\nRole assignment' },
      ],
    },
    s6: {
      h: 'Requestor Workflow',
      sub: 'From sign-up to tracked reservation',
      flow: ['Sign In', 'New Request', 'Select Equipment', 'Conflict Check', 'Submit', 'My Requests'],
      bullets: [
        'Fields: equipment, start/end date & time, purpose, cost code, notes',
        'System checks PENDING and APPROVED reservations for overlaps',
        'Suggests alternative equipment when conflicts are detected',
        'Request number auto-generated; status starts as PENDING',
      ],
    },
    s7: {
      h: 'Approver Workflow',
      sub: 'Governed approval with audit trail',
      boxes: [
        ['Approvals Tab', 'Pending queue'],
        ['Review Request', 'Equipment, dates,\nrequestor, purpose'],
        ['Approve', null],
        ['Reject', null],
        ['Audit Log', 'Actor, status,\ncomments'],
      ],
      note: 'Every action recorded in approval_audit table:\nSUBMITTED → APPROVED / REJECTED / REASSIGNED / CANCELLED / COMPLETED',
    },
    s8: {
      h: 'Conflict Detection Engine',
      sub: 'Real-time double-booking prevention',
      types: [
        { t: 'FULL_OVERLAP', d: 'Complete date overlap\non same equipment' },
        { t: 'PARTIAL_OVERLAP', d: 'Partial date conflict\nneeds resolution' },
        { t: 'ADJACENT', d: 'Back-to-back bookings\nflagged for review' },
      ],
      checksLabel: 'Checks against:',
      bullets: [
        'PENDING and APPROVED reservations on same equipmentId',
        'Automatic alternative_equipment suggestions when conflicts found',
        'reservation_conflict table logs all detected overlaps',
      ],
      timeline: 'Timeline example:',
      existing: 'Existing booking',
      newReq: 'New request (partial overlap)',
    },
    s9: {
      h: 'System Architecture',
      sub: 'Modern cloud-ready stack',
      browser: 'Web Browser (Desktop / Mobile / PWA)',
      app: ['Next.js 16 Application', 'React 19  •  Server Actions  •  shadcn/ui  •  Tailwind CSS v4'],
      bottom: [
        ['PostgreSQL (Neon)', 'Drizzle ORM\n13 tables'],
        ['Better Auth', 'Email/password\nSecure sessions'],
        ['Notifications', 'In-app alerts\nAudit trail'],
      ],
      hosting: 'Hosting: Vercel (recommended)  •  SSL/TLS  •  Connection pooling',
    },
    s10: {
      h: 'Database Model',
      sub: '13 integrated PostgreSQL tables',
      groups: [
        { t: 'Auth (4)', items: 'user, session\naccount, verification' },
        { t: 'Core (5)', items: 'equipment, equipment_availability\nreservation, user_role\nnotification_preference' },
        { t: 'Workflow (4)', items: 'reservation_conflict\nalternative_equipment\napproval_audit, notification' },
      ],
      index: 'Indexed on: equipmentId + dates, requestorId, status, approverId, site, type',
    },
    s11: {
      h: 'Phase 1 — Delivered Features',
      sub: 'Production-ready foundation',
      features: [
        ['Equipment Request Management', 'Cranes, forklifts, manlifts, other'],
        ['Automated Conflict Detection', '3 overlap types + alternatives'],
        ['Approval Workflow', 'Queue, notes, audit trail'],
        ['Role-Based Access', 'Requestor, Approver, Admin'],
        ['Equipment Calendar', 'Filter by site & type'],
        ['Admin Dashboard', 'Equipment CRUD inventory'],
        ['In-App Notifications', 'Status change alerts'],
        ['ExxonMobil Cepu UI', 'Dark theme, EM branding'],
      ],
    },
    s12: {
      h: 'Application Screens',
      sub: 'Key user interfaces',
      screens: [
        'Landing Page — Features, workflow, CTA',
        'Sign In / Sign Up — Better Auth secured',
        'Dashboard — New Request, My Requests, Calendar, Approvals',
        'Reservation Form — Equipment picker, dates, conflict warnings',
        'Approval Queue — Expand, notes, approve/reject',
        'Admin Equipment — Full CRUD inventory management',
      ],
    },
    s13: {
      h: 'Security & Compliance',
      sub: 'Enterprise-grade protections',
      rows: [
        ['Authentication', 'Better Auth — hashed passwords, HTTP-only sessions'],
        ['Authorization', 'Role checks on every server action'],
        ['Audit Trail', 'approval_audit logs all decisions'],
        ['Data Safety', 'Drizzle ORM — parameterized queries'],
        ['Transport', 'HTTPS / SSL in production (Neon + Vercel)'],
        ['Scoping', 'Per-user data isolation'],
      ],
    },
    s14: {
      h: 'Extended Features — Phase 2+',
      sub: 'Recommended enhancements for full operations scale',
      phases: [
        { phase: 'Phase 2A — Operations', items: 'Project-based categorization\nEmail & SMS notifications\nUser role admin UI\nCost code / WBS validation' },
        { phase: 'Phase 2B — Integration', items: 'SAP / ERP integration\nLDAP / Active Directory SSO\niCal calendar export\nMaintenance system link' },
        { phase: 'Phase 3 — Analytics', items: 'Utilization dashboard\nCost tracking & reporting\nEquipment downtime KPIs\nExecutive summary reports' },
        { phase: 'Phase 3 — Mobile', items: 'React Native mobile apps\nPush notifications\nOffline request drafts\nQR equipment scanning' },
      ],
    },
    s15: {
      h: 'Future: Project-Based Categorization',
      sub: 'Organize requests by EMCL project / campaign',
      bullets: [
        'Requestor selects project when submitting equipment request',
        'Approvers filtered to projects they are authorized for',
        'costCode retained for SAP chargeback; project for operations grouping',
        'Enables utilization and cost reporting per project/campaign',
      ],
    },
    s16: {
      h: 'Future: Enterprise Integrations',
      sub: 'Connect to EMCL corporate systems',
      center: ['EMCL Reservation System', 'REST API / Webhooks'],
      integrations: [
        ['SAP ERP', 'Cost codes, WBS,\nasset master'],
        ['Active Directory', 'SSO, org hierarchy'],
        ['Email (SMTP)', 'Approval alerts'],
        ['Maintenance CMMS', 'Equipment status'],
      ],
    },
    s17: {
      h: 'Business Benefits',
      sub: 'Measurable value for EMCL operations',
      benefits: [
        ['⏱ Faster bookings', 'Reduce manual lifting plan admin time'],
        ['📅 Fewer conflicts', 'Higher equipment utilization'],
        ['✅ Clear approvals', 'Accountability & compliance'],
        ['👁 Central visibility', 'Cross-site planning'],
        ['📋 Digital audit trail', 'Easier regulatory audits'],
        ['📈 Scalable platform', 'Add sites, equipment, users'],
      ],
    },
    s18: {
      h: 'Deployment Plan',
      sub: 'Suggested rollout timeline',
      timeline: [
        { w: 'Week 1–2', t: 'Pilot Setup', d: 'Configure Neon DB, roles, equipment list' },
        { w: 'Week 2–3', t: 'UAT', d: 'Requestor + Approver end-to-end testing' },
        { w: 'Week 3', t: 'Training', d: 'Role-based user sessions' },
        { w: 'Week 4+', t: 'Go-Live', d: 'Vercel production deployment' },
        { w: 'Q+', t: 'Phase 2', d: 'Project module, email, SAP integration' },
      ],
    },
    s19: {
      h: 'Live Demo Agenda',
      sub: '10-minute walkthrough',
      demo: [
        '1. Landing page & ExxonMobil Cepu branding',
        '2. Sign up / Sign in (Better Auth)',
        '3. Requestor: submit new equipment reservation',
        '4. Conflict detection warning (if applicable)',
        '5. Approver: review & approve in Approvals tab',
        '6. Requestor: view updated status in My Requests',
        '7. Equipment calendar — availability by site',
        '8. Admin: equipment inventory management',
      ],
    },
    s20: {
      h: 'Next Steps',
      sub: 'Path to production',
      bullets: [
        'Approve pilot scope — select site(s), users, and equipment inventory',
        'Assign roles — Requestors, Approvers, Admins in user_role table',
        'Run UAT — full request → approve → calendar flow',
        'Conduct role-based training sessions',
        'Deploy to Vercel production with Neon PostgreSQL',
        'Plan Phase 2 — project categorization, email alerts, SAP integration',
      ],
      contact: 'Contact: ExxonMobil Cepu Limited Operations Team',
    },
    s21: {
      h: 'Questions & Answers',
      sub: 'EMCL Heavy Equipment Reservation System',
    },
  },
  id: {
    meta: {
      title: 'Sistem Reservasi Alat Berat EMCL',
      subject: 'Presentasi Pelanggan',
      outfile: 'EMCL-Sistem-Reservasi-Alat-Berat-ID.pptx',
    },
    footer: 'ExxonMobil Cepu Limited — Penggunaan Internal',
    s1: {
      title: 'Sistem Reservasi\nAlat Berat EMCL',
      subtitle: 'Platform digital untuk crane, forklift, manlift & operasi pengangkatan',
      date: 'ExxonMobil Cepu Limited  |  Presentasi Pelanggan  |  Juni 2026',
    },
    s2: {
      h: 'Ringkasan Eksekutif',
      sub: 'Menggantikan software lifting plan lama dengan platform web modern',
      metrics: ['Tabel Database', 'Peran Pengguna', 'Jenis Alat', 'Jejak Audit'],
      bullets: [
        'Pemesanan alat terpusat di seluruh lokasi EMCL Cepu',
        'Deteksi konflik otomatis mencegah double-booking',
        'Alur persetujuan terstruktur dengan pencatatan kepatuhan penuh',
        'Fase 1 selesai — siap pilot di Vercel + Neon PostgreSQL',
      ],
    },
    s3: {
      h: 'Tantangan Bisnis',
      sub: 'Mengapa sistem baru diperlukan',
      rows: [
        ['Rencana lifting manual / legacy', 'Keterlambatan, kesalahan, visibilitas rendah'],
        ['Double-booking alat berat', 'Konflik jadwal & downtime'],
        ['Proses persetujuan tidak jelas', 'Keputusan lambat, risiko kepatuhan'],
        ['Visibilitas lintas lokasi terbatas', 'Sulit merencanakan penggunaan alat'],
        ['Pelacakan kertas / email', 'Jejak audit lemah untuk inspeksi'],
      ],
    },
    s4: {
      h: 'Gambaran Solusi',
      sub: 'Siklus reservasi alat berat dari awal hingga akhir',
      steps: [
        ['1. Permintaan', 'Pilih alat\n& rentang tanggal'],
        ['2. Deteksi', 'Cek konflik\n& alternatif'],
        ['3. Setujui', 'Review approver\n& keputusan'],
        ['4. Lacak', 'Kalender, status\n& notifikasi'],
      ],
      banner: 'Portal web tunggal — desktop & mobile (PWA)  •  Akses berbasis peran  •  UI bermerek ExxonMobil Cepu',
    },
    s5: {
      h: 'Peran Pengguna & Kontrol Akses',
      sub: 'Tiga peran — satu portal login',
      roles: [
        { t: 'REQUESTOR', items: 'Ajukan permintaan\nLihat Permintaan Saya\nKalender alat' },
        { t: 'APPROVER', items: 'Semua fitur Requestor\nAntrian persetujuan\nSetujui / Tolak + catatan' },
        { t: 'ADMIN', items: 'Semua fitur Approver\nCRUD inventaris alat\nPenugasan peran' },
      ],
    },
    s6: {
      h: 'Alur Requestor',
      sub: 'Dari pendaftaran hingga reservasi tercatat',
      flow: ['Masuk', 'Permintaan Baru', 'Pilih Alat', 'Cek Konflik', 'Kirim', 'Permintaan Saya'],
      bullets: [
        'Field: alat, tanggal/waktu mulai & selesai, tujuan, kode biaya, catatan',
        'Sistem memeriksa reservasi PENDING dan APPROVED untuk tumpang tindih',
        'Menyarankan alat alternatif saat konflik terdeteksi',
        'Nomor permintaan otomatis; status awal PENDING',
      ],
    },
    s7: {
      h: 'Alur Approver',
      sub: 'Persetujuan terkontrol dengan jejak audit',
      boxes: [
        ['Tab Persetujuan', 'Antrian pending'],
        ['Review Permintaan', 'Alat, tanggal,\nrequestor, tujuan'],
        ['Setujui', null],
        ['Tolak', null],
        ['Log Audit', 'Aktor, status,\ncatatan'],
      ],
      note: 'Setiap aksi dicatat di tabel approval_audit:\nSUBMITTED → APPROVED / REJECTED / REASSIGNED / CANCELLED / COMPLETED',
    },
    s8: {
      h: 'Mesin Deteksi Konflik',
      sub: 'Pencegahan double-booking secara real-time',
      types: [
        { t: 'FULL_OVERLAP', d: 'Tumpang tindih penuh\ntanggal pada alat sama' },
        { t: 'PARTIAL_OVERLAP', d: 'Konflik tanggal sebagian\nperlu resolusi' },
        { t: 'ADJACENT', d: 'Pemesanan berurutan\nditandai untuk review' },
      ],
      checksLabel: 'Memeriksa terhadap:',
      bullets: [
        'Reservasi PENDING dan APPROVED pada equipmentId yang sama',
        'Saran alternative_equipment otomatis saat konflik ditemukan',
        'Tabel reservation_conflict mencatat semua tumpang tindih',
      ],
      timeline: 'Contoh timeline:',
      existing: 'Pemesanan existing',
      newReq: 'Permintaan baru (overlap sebagian)',
    },
    s9: {
      h: 'Arsitektur Sistem',
      sub: 'Stack modern siap cloud',
      browser: 'Web Browser (Desktop / Mobile / PWA)',
      app: ['Aplikasi Next.js 16', 'React 19  •  Server Actions  •  shadcn/ui  •  Tailwind CSS v4'],
      bottom: [
        ['PostgreSQL (Neon)', 'Drizzle ORM\n13 tabel'],
        ['Better Auth', 'Email/password\nSesi aman'],
        ['Notifikasi', 'Alert in-app\nJejak audit'],
      ],
      hosting: 'Hosting: Vercel (disarankan)  •  SSL/TLS  •  Connection pooling',
    },
    s10: {
      h: 'Model Database',
      sub: '13 tabel PostgreSQL terintegrasi',
      groups: [
        { t: 'Auth (4)', items: 'user, session\naccount, verification' },
        { t: 'Inti (5)', items: 'equipment, equipment_availability\nreservation, user_role\nnotification_preference' },
        { t: 'Workflow (4)', items: 'reservation_conflict\nalternative_equipment\napproval_audit, notification' },
      ],
      index: 'Diindeks: equipmentId + tanggal, requestorId, status, approverId, site, type',
    },
    s11: {
      h: 'Fase 1 — Fitur yang Sudah Dibangun',
      sub: 'Fondasi siap produksi',
      features: [
        ['Manajemen Permintaan Alat', 'Crane, forklift, manlift, lainnya'],
        ['Deteksi Konflik Otomatis', '3 jenis overlap + alternatif'],
        ['Alur Persetujuan', 'Antrian, catatan, jejak audit'],
        ['Akses Berbasis Peran', 'Requestor, Approver, Admin'],
        ['Kalender Alat', 'Filter berdasarkan lokasi & jenis'],
        ['Dashboard Admin', 'CRUD inventaris alat'],
        ['Notifikasi In-App', 'Alert perubahan status'],
        ['UI ExxonMobil Cepu', 'Tema gelap, branding EM'],
      ],
    },
    s12: {
      h: 'Layar Aplikasi',
      sub: 'Antarmuka pengguna utama',
      screens: [
        'Halaman Utama — Fitur, alur kerja, CTA',
        'Masuk / Daftar — Keamanan Better Auth',
        'Dashboard — Permintaan Baru, Permintaan Saya, Kalender, Persetujuan',
        'Form Reservasi — Pilih alat, tanggal, peringatan konflik',
        'Antrian Persetujuan — Expand, catatan, setujui/tolak',
        'Admin Alat — Manajemen inventaris CRUD penuh',
      ],
    },
    s13: {
      h: 'Keamanan & Kepatuhan',
      sub: 'Perlindungan tingkat enterprise',
      rows: [
        ['Autentikasi', 'Better Auth — password di-hash, sesi HTTP-only'],
        ['Otorisasi', 'Cek peran di setiap server action'],
        ['Jejak Audit', 'approval_audit mencatat semua keputusan'],
        ['Keamanan Data', 'Drizzle ORM — query terparameterisasi'],
        ['Transport', 'HTTPS / SSL di produksi (Neon + Vercel)'],
        ['Isolasi Data', 'Pemisahan data per pengguna'],
      ],
    },
    s14: {
      h: 'Fitur Perluasan — Fase 2+',
      sub: 'Peningkatan yang disarankan untuk skala operasi penuh',
      phases: [
        { phase: 'Fase 2A — Operasi', items: 'Kategorisasi berbasis proyek\nNotifikasi email & SMS\nUI admin peran pengguna\nValidasi kode biaya / WBS' },
        { phase: 'Fase 2B — Integrasi', items: 'Integrasi SAP / ERP\nSSO LDAP / Active Directory\nEkspor kalender iCal\nKoneksi sistem maintenance' },
        { phase: 'Fase 3 — Analitik', items: 'Dashboard utilisasi\nPelacakan biaya & laporan\nKPI downtime alat\nLaporan ringkasan eksekutif' },
        { phase: 'Fase 3 — Mobile', items: 'Aplikasi mobile React Native\nPush notification\nDraft permintaan offline\nScan QR peralatan' },
      ],
    },
    s15: {
      h: 'Masa Depan: Kategorisasi Proyek',
      sub: 'Kelompokkan permintaan berdasarkan proyek / kampanye EMCL',
      bullets: [
        'Requestor memilih proyek saat mengajukan permintaan alat',
        'Approver difilter ke proyek yang mereka berwenang',
        'costCode tetap untuk chargeback SAP; proyek untuk pengelompokan operasi',
        'Memungkinkan laporan utilisasi dan biaya per proyek/kampanye',
      ],
    },
    s16: {
      h: 'Masa Depan: Integrasi Enterprise',
      sub: 'Terhubung ke sistem korporat EMCL',
      center: ['Sistem Reservasi EMCL', 'REST API / Webhooks'],
      integrations: [
        ['SAP ERP', 'Kode biaya, WBS,\nasset master'],
        ['Active Directory', 'SSO, hierarki org'],
        ['Email (SMTP)', 'Alert persetujuan'],
        ['Maintenance CMMS', 'Status peralatan'],
      ],
    },
    s17: {
      h: 'Manfaat Bisnis',
      sub: 'Nilai terukur untuk operasi EMCL',
      benefits: [
        ['⏱ Pemesanan lebih cepat', 'Kurangi waktu admin lifting plan manual'],
        ['📅 Konflik lebih sedikit', 'Utilisasi alat lebih tinggi'],
        ['✅ Persetujuan jelas', 'Akuntabilitas & kepatuhan'],
        ['👁 Visibilitas terpusat', 'Perencanaan lintas lokasi'],
        ['📋 Jejak audit digital', 'Audit regulasi lebih mudah'],
        ['📈 Platform skalabel', 'Tambah lokasi, alat, pengguna'],
      ],
    },
    s18: {
      h: 'Rencana Deployment',
      sub: 'Timeline peluncuran yang disarankan',
      timeline: [
        { w: 'Minggu 1–2', t: 'Setup Pilot', d: 'Konfigurasi Neon DB, peran, daftar alat' },
        { w: 'Minggu 2–3', t: 'UAT', d: 'Pengujian end-to-end Requestor + Approver' },
        { w: 'Minggu 3', t: 'Pelatihan', d: 'Sesi pengguna berdasarkan peran' },
        { w: 'Minggu 4+', t: 'Go-Live', d: 'Deployment produksi Vercel' },
        { w: 'Kuartal+', t: 'Fase 2', d: 'Modul proyek, email, integrasi SAP' },
      ],
    },
    s19: {
      h: 'Agenda Demo Langsung',
      sub: 'Walkthrough 10 menit',
      demo: [
        '1. Halaman utama & branding ExxonMobil Cepu',
        '2. Daftar / Masuk (Better Auth)',
        '3. Requestor: ajukan reservasi alat baru',
        '4. Peringatan deteksi konflik (jika ada)',
        '5. Approver: review & setujui di tab Persetujuan',
        '6. Requestor: lihat status terbaru di Permintaan Saya',
        '7. Kalender alat — ketersediaan per lokasi',
        '8. Admin: manajemen inventaris alat',
      ],
    },
    s20: {
      h: 'Langkah Selanjutnya',
      sub: 'Menuju produksi',
      bullets: [
        'Setujui ruang lingkup pilot — pilih lokasi, pengguna, inventaris alat',
        'Tetapkan peran — Requestor, Approver, Admin di tabel user_role',
        'Jalankan UAT — alur permintaan → setujui → kalender',
        'Laksanakan pelatihan berbasis peran',
        'Deploy ke produksi Vercel dengan Neon PostgreSQL',
        'Rencanakan Fase 2 — kategorisasi proyek, alert email, integrasi SAP',
      ],
      contact: 'Kontak: Tim Operasi ExxonMobil Cepu Limited',
    },
    s21: {
      h: 'Tanya Jawab',
      sub: 'Sistem Reservasi Alat Berat EMCL',
    },
  },
}

export function getLocale(lang) {
  return locales[lang === 'id' ? 'id' : 'en']
}
